# Data Preperation for News Classification

In [2]:
import collections
import numpy as np
import pandas as pd
import re

from argparse import Namespace

In [3]:
args = Namespace(
    raw_dataset_csv="data/ag_news/news.csv",
    train_proportion=0.7,
    val_proportion=0.15,
    test_proportion=0.15,
    output_munged_csv="data/ag_news/news_with_splits.csv",
    seed=1337
)

In [4]:
# Read raw data
news = pd.read_csv(args.raw_dataset_csv, header=0)

In [5]:
news.head()

   category                                              title
0  Business  Wall St. Bears Claw Back Into the Black (Reuters)
1  Business  Carlyle Looks Toward Commercial Aerospace (Reu...
2  Business    Oil and Economy Cloud Stocks' Outlook (Reuters)
3  Business  Iraq Halts Oil Exports from Main Southern Pipe...
4  Business  Oil prices soar to all-time record, posing new...

In [6]:
# Unique classes
set(news.category)

{'Business', 'Sci/Tech', 'Sports', 'World'}

In [7]:
# Splitting train by category
# Create dict
by_category = collections.defaultdict(list)
for _, row in news.iterrows():
    by_category[row.category].append(row.to_dict())

In [8]:
by_category

defaultdict(list,
            {'Business': [{'category': 'Business',
               'title': 'Wall St. Bears Claw Back Into the Black (Reuters)'},
              {'category': 'Business',
               'title': 'Carlyle Looks Toward Commercial Aerospace (Reuters)'},
              {'category': 'Business',
               'title': "Oil and Economy Cloud Stocks' Outlook (Reuters)"},
              {'category': 'Business',
               'title': 'Iraq Halts Oil Exports from Main Southern Pipeline (Reuters)'},
              {'category': 'Business',
               'title': 'Oil prices soar to all-time record, posing new menace to US economy (AFP)'},
              {'category': 'Business',
               'title': 'Stocks End Up, But Near Year Lows (Reuters)'},
              {'category': 'Business',
               'title': 'Money Funds Fell in Latest Week (AP)'},
              {'category': 'Business',
               'title': 'Fed minutes show dissent over inflation (USATODAY.com)'},
              {'category': 'Business', 'title': 'Safety Net (Forbes.com)'},
              {'category': 'Business',
               'title': 'Wall St. Bears Claw Back Into the Black'},
              {'category': 'Business',
               'title': "Oil and Economy Cloud Stocks' Outlook"},
              {'category': 'Business',
               'title': 'No Need for OPEC to Pump More-Iran Gov'},
              {'category': 'Business',
               'title': 'Non-OPEC Nations Should Up Output-Purnomo'},
              {'category': 'Business',
               'title': 'Google IPO Auction Off to Rocky Start'},
              {'category': 'Business',
               'title': 'Dollar Falls Broadly on Record Trade Gap'},
              {'category': 'Business', 'title': 'Rescuing an Old Saver'},
              {'category': 'Business',
               'title': 'Kids Rule for Back-to-School'},
              {'category': 'Business',
               'title': 'In a Down Market, Head Toward Value Funds'},
              {'category': 'Business',
               'title': 'US trade deficit swells in June'},
              {'category': 'Business',
               'title': "Shell 'could be target for Total'"},
              {'category': 'Business',
               'title': 'Google IPO faces Playboy slip-up'},
              {'category': 'Business',
               'title': 'Eurozone economy keeps growing'},
              {'category': 'Business', 'title': 'Expansion slows in Japan'},
              {'category': 'Business',
               'title': 'Rand falls on shock SA rate cut'},
              {'category': 'Business',
               'title': 'Car prices down across the board'},
              {'category': 'Business',
               'title': 'South Korea lowers interest rates'},
              {'category': 'Business',
               'title': 'Google auction begins on Friday'},
              {'category': 'Business',
               'title': 'HP shares tumble on profit news'},
              {'category': 'Business',
               'title': 'Mauritian textile firm cuts jobs'},
              {'category': 'Business',
               'title': 'Chad seeks refugee aid from IMF'},
              {'category': 'Business',
               'title': 'Japan nuclear firm shuts plants'},
              {'category': 'Business',
               'title': 'Veteran inventor in market float'},
              {'category': 'Business',
               'title': 'Saudi Arabia to open up oil taps'},
              {'category': 'Business',
               'title': 'Saudi phone sector gets \\$1bn lift'},
              {'category': 'Business',
               'title': 'Indians fill rail skills shortage'},
              {'category': 'Business', 'title': 'Steady as they go'},
              {'category': 'Business',
               'title': "Google IPO: Type in 'confusing,' 'secrecy'"},
              {'category': 'Business', 'title': "A bargain hunter's paradise"},
              {'category': 'Business',
               'title': 'Researchers seek to untangle the e-mail thread'},
              {'category': 'Business',
               'title': 'Microsoft Corp. 2.0: a kinder corporate culture'},
              {'category': 'Business', 'title': 'Letters'},
              {'category': 'Business',
               'title': 'Somewhere between gleam and gloom'},
              {'category': 'Business',
               'title': 'Technology company sues five ex-employees '},
              {'category': 'Business',
               'title': 'Grant to aid Lynn Central Square'},
              {'category': 'Business',
               'title': 'State grant to aid Lynn; Bank gives Salem \\$10k'},
              {'category': 'Business',
               'title': "A New Legal Chapter for a 90's Flameout"},
              {'category': 'Business',
               'title': 'Will Russia, the Oil Superpower, Flex Its Muscles?'},
              {'category': 'Business',
               'title': 'Switching Titles, if Not Gears, at Dell'},
              {'category': 'Business',
               'title': 'For Sale: The Ultimate Status Symbol'},
              {'category': 'Business', 'title': 'Quality Gets Swept Away'},
              {'category': 'Business', 'title': 'Making Your Insurer Pay'},
              {'category': 'Business', 'title': 'Delightful Dell'},
              {'category': 'Business', 'title': "Chrysler's Bling King"},
              {'category': 'Business',
               'title': "What's Cool In the Pool ... ... And Hot On the Deck"},
              {'category': 'Business', 'title': 'The Age of Doom'},
              {'category': 'Business', 'title': "Hip Hop's Online Shop"},
              {'category': 'Business', 'title': 'Stoking the Steamroller'},
              {'category': 'Business', 'title': 'Coming to The Rescue'},
              {'category': 'Business',
               'title': 'The New Customers Are In Town'},
              {'category': 'Business',
               'title': 'Barrel of Monkeys, 2004 Edition: Notes on Philippine Elections'},
              {'category': 'Business',
               'title': 'Oldsmobile: The final parking lot'},
              {'category': 'Business',
               'title': 'Not All Jobs Belong To The White Man: Asian Minorities, Affirmative Action, And The Quest For Parity At Work'},
              {'category': 'Business',
               'title': 'Downhome Pinoy Blues, Intersecting Life Paths, and Heartbreak Songs'},
              {'category': 'Business',
               'title': 'The Real Time Modern Manila Blues: Bill Monroe Meets Muddy Waters in the Orient'},
              {'category': 'Business',
               'title': 'Best Asian Tourism Destinations'},
              {'category': 'Business',
               'title': 'What are the best cities for business in Asia?'},
              {'category': 'Business', 'title': 'IT alligator tales'},
              {'category': 'Business',
               'title': 'IT Myth 5: Most IT projects fail'},
              {'category': 'Business',
               'title': 'BEA grabs CA exec to head product group'},
              {'category': 'Business',
               'title': 'Autodesk tackles project collaboration'},
              {'category': 'Business',
               'title': "U.K.'s NHS taps Gartner to help plan \\$9B IT overhaul"},
              {'category': 'Business',
               'title': 'Play Boys: Google IPO a Go Anyway'},
              {'category': 'Business', 'title': 'More Big Boobs in Playboy'},
              {'category': 'Business',
               'title': 'Dutch Firm Beats Apple to Punch'},
              {'category': 'Business', 'title': 'HP to Buy Synstar'},
              {'category': 'Business',
               'title': 'A Personal Operator From Verizon'},
              {'category': 'Business', 'title': 'Paid Search Growth May Slow'},
              {'category': 'Business',
               'title': 'Fark Sells Out. France Surrenders'},
              {'category': 'Business',
               'title': 'Strategies for a Sideways Market (Reuters)'},
              {'category': 'Business',
               'title': 'Art Looks Like Fine Investment for Funds (Reuters)'},
              {'category': 'Business',
               'title': "Oil and Economy Cloud Stocks' Outlook (Reuters)"},
              {'category': 'Business',
               'title': 'Strategies for a Sideways Market'},
              {'category': 'Business',
               'title': 'Art Looks Like Fine Investment for Funds'},
              {'category': 'Business',
               'title': "Oil and Economy Cloud Stocks' Outlook"},
              {'category': 'Business',
               'title': 'Funds: Are Bond Funds Hazardous?'},
              {'category': 'Business',
               'title': 'Shippers: Venezuela Oil Unfazed by Poll'},
              {'category': 'Business',
               'title': 'Shippers: Venezuela Oil Unfazed by Poll (Reuters)'},
              {'category': 'Business',
               'title': 'Dollar Falls to Fresh Low Vs Euro (Reuters)'},
              {'category': 'Business',
               'title': 'Nikkei Falls Over 1 Pct on Oil Worries'},
              {'category': 'Business',
               'title': "The Region's Highest-Paid Executives"},
              {'category': 'Business',
               'title': "As XM Stock Recovered, Executives' Pay Modest"},
              {'category': 'Business',
               'title': 'Lucrative Cash Package Came as Fairchild Reported \\$53.2 Million Loss'},
              {'category': 'Business',
               'title': 'Board Members, Executives and Family Members Can Still Benefit'},
              {'category': 'Business',
               'title': 'Survey Estimates Values of Options, Excludes Exercises'},
              {'category': 'Business',
               'title': 'Government Spending Up Sharply Locally'},
              {'category': 'Business',
               'title': 'Nikkei Falls Over 1 Pct on Oil Worries (Reuters)'},
              {'category': 'Business',
               'title': 'Nikkei Down at Midday on Oil Worries'},
              {'category': 'Business',
               'title': 'Caterpillar Union Rejects Contract Offer'},
              {'category': 'Business',
               'title': 'NYMEX Crude Hits Record \\$46.76'},
              {'category': 'Business',
               'title': 'Caterpillar Union Rejects Contract Offer'},
              {'category': 'Business',
               'title': "GM's Made-In-China Cadillacs in Early '05"},
              {'category': 'Business',
               'title': 'Wal-Mart Tries to Shine Its Image by Supporting Public Broadcasting'},
              {'category': 'Business',
               'title': 'Muddling Through (or Not): Mid-2004 Update on the Philippines'},
              {'category': 'Business',
               'title': "In Google's Auction, It's Not Easy to Tell a Bid From a Bet"},
              {'category': 'Business',
               'title': 'Nikkei Hits 3-Mth Closing Low'},
              {'category': 'Business',
               'title': 'Stocks Fall as Oil Hits High'},
              {'category': 'Business',
               'title': 'Stocks Fall as Oil Hits High (Reuters)'},
              {'category': 'Business',
               'title': 'Iranian economic reform falters'},
              {'category': 'Business', 'title': 'Space-age sport '},
              {'category': 'Business',
               'title': 'Eyes tired? Musical alerts ease computer user #146;s day'},
              {'category': 'Business',
               'title': 'As money-raisers, 2004 #146;s initial offerings fall short'},
              {'category': 'Business',
               'title': 'Internet publishing attracting academics'},
              {'category': 'Business',
               'title': 'Computers with multiple personalities'},
              {'category': 'Business',
               'title': 'Oil Prices Hit Record (Reuters)'},
              {'category': 'Business',
               'title': 'Swatch tax complaint dismissed'},
              {'category': 'Business',
               'title': 'Small firms struggle as oil soars'},
              {'category': 'Business',
               'title': 'Microsoft takes down SP2 swappers'},
              {'category': 'Business',
               'title': 'Europe and US in aircraft aid row'},
              {'category': 'Business',
               'title': "Lowe's Second-Quarter Profit Rises (Reuters)"},
              {'category': 'Business',
               'title': 'Stocks Seen Little Changed; Oil Weighs'},
              {'category': 'Business',
               'title': "Lowe's Second-Quarter Profit Rises"},
              {'category': 'Business', 'title': 'Oil Prices Hold Near Record'},
              {'category': 'Business',
               'title': 'BA workers approve holiday strike'},
              {'category': 'Business',
               'title': "Lowe's 2Q Earnings Higher on Home Market (AP)"},
              {'category': 'Business', 'title': 'Sri Lanka hit by oil strike'},
              {'category': 'Business',
               'title': 'Cost Cuts Boost Kmart Quarterly Profit (Reuters)'},
              {'category': 'Business',
               'title': 'Cost Cuts Boost Kmart Quarterly Profit'},
              {'category': 'Business',
               'title': 'Wall Street to Open Little Changed'},
              {'category': 'Business',
               'title': 'Sysco Profit Rises; Sales Have Slowed'},
              {'category': 'Business',
               'title': "Lowe's Profit Rises But Trails Estimates"},
              {'category': 'Business',
               'title': 'Kmart Swings to Second-Quarter Profit (AP)'},
              {'category': 'Business',
               'title': 'Wal-Mart Maintains August Sales Forecast (Reuters)'},
              {'category': 'Business',
               'title': 'Cost Cuts Help Kmart Post Profit'},
              {'category': 'Business',
               'title': 'Allstate Says Charley Could Hurt Results'},
              {'category': 'Business',
               'title': 'Hungarian central bank cuts key interest rate by half percentage point (AFP)'},
              {'category': 'Business',
               'title': 'CompUSA Stores to Sell Gateway PCs (Reuters)'},
              {'category': 'Business',
               'title': 'CompUSA Stores to Sell Gateway PCs'},
              {'category': 'Business',
               'title': 'Kmart Posts Profit After Cost Cuts'},
              {'category': 'Business',
               'title': 'LifePoint in \\$1.1 Billion Province Deal'},
              {'category': 'Business',
               'title': 'Stocks Set to Open Little Changed'},
              {'category': 'Business',
               'title': "Sysco Corp.'s 4Q Profit Up 16 Percent"},
              {'category': 'Business',
               'title': 'Stocks Open Near Flat as Oil Near Record'},
              {'category': 'Business',
               'title': 'Indonesia urges debt flexibility'},
              {'category': 'Business', 'title': 'Oil Holds Near Record Level'},
              {'category': 'Business', 'title': 'Ride This Gem'},
              {'category': 'Business',
               'title': 'Insurers Begin Tallying Charley Losses (Reuters)'},
              {'category': 'Business',
               'title': 'KMart Posts Profit; Cash Pile Grows'},
              {'category': 'Business',
               'title': 'Thomson Buys Test Provider Capstar'},
              {'category': 'Business',
               'title': "Lowe's Reports Increase in Second-Quarter Net Income"},
              {'category': 'Business',
               'title': "Lowe's Net Trails Views, But Shares Rise"},
              {'category': 'Business',
               'title': 'KMart Posts Profit; Cash Pile Grows (Reuters)'},
              {'category': 'Business',
               'title': 'Oil Slips from Record High of \\$46.30'},
              {'category': 'Business',
               'title': 'Stocks Gain as Oil Prices Ease'},
              {'category': 'Business',
               'title': 'How to Hire a Financial Planner (The Motley Fool)'},
              {'category': 'Business',
               'title': 'Daimler Nets \\$900 Mln Via Hyundai Sale'},
              {'category': 'Business', 'title': 'The Internet Is Calling'},
              {'category': 'Business', 'title': 'A Stereo with a Brain'},
              {'category': 'Business', 'title': 'The Sponsor Moves In'},
              {'category': 'Business',
               'title': 'Stocks Higher on Oil Price Relief'},
              {'category': 'Business', 'title': 'Is 4Kids 4 Investors?'},
              {'category': 'Business',
               'title': 'Charley Sends Mobile Home Stocks Soaring'},
              {'category': 'Business',
               'title': 'Stocks Higher on Oil Price Relief (Reuters)'},
              {'category': 'Business',
               'title': 'Intelsat to Be Bought for  #36;5 Billion (Reuters)'},
              {'category': 'Business',
               'title': 'Intelsat to Be Bought for \\$5 Billion'},
              {'category': 'Business',
               'title': 'Stamps.com Asks You to Picture This'},
              {'category': 'Business',
               'title': 'Will Schwab Reward Patience?'},
              {'category': 'Business',
               'title': 'Stocks Up, Oil Price Ease Gives Relief'},
              {'category': 'Business',
               'title': 'KMart Posts Profit; Cash Hits \\$2.6 Bln'},
              {'category': 'Business', 'title': 'No Respite for Microsoft'},
              {'category': 'Business', 'title': 'Overland Bullish on Tech'},
              {'category': 'Business',
               'title': "Lowe's Reports 18 Pct. Hike in Profits"},
              {'category': 'Business',
               'title': "Toymakers' Stocks Hit Lows on Downgrade"},
              {'category': 'Business',
               'title': 'U.S. Stocks Rebound as Oil Prices Ease'},
              {'category': 'Business',
               'title': 'Dollar Rises Vs Euro After Asset Data'},
              {'category': 'Business',
               'title': "Venezuela's Chavez Wins Recall Referendum"},
              {'category': 'Business',
               'title': 'Halliburton Says Army Suspends Withhold Threat'},
              {'category': 'Business',
               'title': 'Belo Takes Charge for Advertising Refunds'},
              {'category': 'Business',
               'title': 'LifePoint to Buy Rival for \\$1 Bln'},
              {'category': 'Business',
               'title': "Venezuela's Chavez Wins Recall Referendum (Reuters)"},
              {'category': 'Business',
               'title': 'Private Firms to Buy Intelsat for \\$3 Bln'},
              {'category': 'Business', 'title': "Taco Bell's Blue Dew"},
              {'category': 'Business', 'title': 'Executive Compensation'},
              {'category': 'Business',
               'title': 'Kmart: Retail or Real Estate?'},
              {'category': 'Business',
               'title': 'Equity Firms to Buy Intelsat for \\$3.1 Bln'},
              {'category': 'Business',
               'title': 'Halliburton: Army  to Give Company More Time to Resolve Billing Dispute'},
              {'category': 'Business',
               'title': 'Sysco Profit Rises; Sales Volume Flat'},
              {'category': 'Business',
               'title': 'Treasuries Fall as Oil Retreats (Reuters)'},
              {'category': 'Business', 'title': 'Product Previews, 8/16/2004'},
              {'category': 'Business',
               'title': 'Insurers: Charley Claims at About \\$7 Bln'},
              {'category': 'Business',
               'title': 'Stocks Bounce Back as Oil Retreats'},
              {'category': 'Business',
               'title': 'Google Could Make Its Market Debut Wed.'},
              {'category': 'Business',
               'title': 'Google Could Make Its Market Debut Wed. (Reuters)'},
              {'category': 'Business',
               'title': "Lowe's Net Income Up 18 Percent"},

In [9]:
# Create split data
final_list = []
np.random.seed(args.seed)
for _, item_list in sorted(by_category.items()):
    np.random.shuffle(item_list)
    n = len(item_list)
    n_train = int(args.train_proportion*n)
    n_val = int(args.val_proportion*n)
    n_test = int(args.test_proportion*n)
    
    # Give data point a split attribute
    for item in item_list[:n_train]:
        item['split'] = 'train'
    for item in item_list[n_train:n_train+n_val]:
        item['split'] = 'val'
    for item in item_list[n_train+n_val:]:
        item['split'] = 'test'  
    
    # Add to final list
    final_list.extend(item_list)

In [10]:
# Write split data to file
final_news = pd.DataFrame(final_list)

In [11]:
final_news.split.value_counts()

split
train    84000
val      18000
test     18000
Name: count, dtype: int64

In [12]:
# Preprocess the reviews
def preprocess_text(text):
    text = ' '.join(word.lower() for word in text.split(" "))
    text = re.sub(r"([.,!?])", r" \1 ", text)
    text = re.sub(r"[^a-zA-Z.,!?]+", r" ", text)
    return text
    
final_news.title = final_news.title.apply(preprocess_text)

In [13]:
final_news.head()

   category                                title  split
0  Business  jobs , tax cuts key issues for bush  train
1  Business    jarden buying mr . coffee s maker  train
2  Business    retail sales show festive fervour  train
3  Business  intervoice s customers come calling  train
4  Business    boeing expects air force contract  train

In [14]:
# Write munged data to CSV
final_news.to_csv(args.output_munged_csv, index=False)